services:
  web:
    image: gitea.huiyim.cn/gaohuipeng/prompt:latest
    container_name: prompt-platform
    restart: always
    ports:
      - "8002:8002"
    environment:
      - NUXT_SESSION_PASSWORD=7d3a0f7b-9e1c-4b3a-8f5d-2c6e9a7f1b4d_secure
      - DB_HOST=192.144.167.138
      - DB_PORT=7306
      - DB_USER=root
      - DB_PASSWORD=Gaohp@990421
      - DB_NAME=prompt_dev
